(function(){
'use strict';
var KEY="ttf100",APP="Treino Tracker Feminino",VERSION="1.05",GOALS="Treinos: quarta a domingo<br>Tempo: 35 min<br>Descanso: 60–75 s; exercícios pesados até 90 s",FILE_PREFIX="treino-feminino",IS_MALE=false;
function read(){try{var d=JSON.parse(localStorage.getItem(KEY)||'{"sessions":{},"measurements":[]}');d.sessions=d.sessions||{};d.measurements=d.measurements||[];return d}catch(e){return {sessions:{},measurements:[]}}}
function write(d){localStorage.setItem(KEY,JSON.stringify(d));try{if(IS_MALE&&typeof data!=='undefined')data=d;if(!IS_MALE&&typeof D!=='undefined')D=d}catch(e){}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function datePt(v){try{return new Date(v).toLocaleDateString('pt-BR')}catch(e){return '—'}}
function download(name,text,type){var blob=new Blob([text],{type:type||'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1000)}
function exerciseName(day,i){try{if(IS_MALE&&typeof workouts!=='undefined'&&workouts[day])return workouts[day].items[i][0];if(!IS_MALE&&typeof W!=='undefined'&&W[day])return W[day].items[i][0]}catch(e){}return 'Exercício '+(Number(i)+1)}
function csv(){var d=read(),rows=[['Tipo','Data','Treino','Exercício','Série','Reps','RPE','Carga kg','Equipamento','Peso kg','Gordura %','Observação','Concluída']];Object.keys(d.sessions).forEach(function(k){var s=d.sessions[k],parts=k.split('_'),dt=parts[0],day=parts.slice(1).join('_');Object.keys(s.ex||{}).forEach(function(i){var ex=s.ex[i]||{};(ex.sets||[]).forEach(function(x,j){rows.push(['TREINO',dt,day,exerciseName(day,i),j+1,x.reps||'',x.rpe||'',x.load||'',ex.variant||'','','','',x.done?'SIM':'NÃO'])})})});d.measurements.forEach(function(m){rows.push(['AVALIAÇÃO',(m.date||'').slice(0,10),'','','','','','','',m.weight||'',m.fat||'',m.note||'',''])});var out=rows.map(function(r){return r.map(function(x){return '"'+String(x).replace(/"/g,'""')+'"'}).join(';')}).join('\n');download(FILE_PREFIX+'-dados-'+new Date().toISOString().slice(0,10)+'.csv','\ufeff'+out,'text/csv;charset=utf-8')}
function backup(){var d=read(),copy=JSON.parse(JSON.stringify(d));copy._backup={app:APP,createdAt:new Date().toISOString(),version:VERSION};download(FILE_PREFIX+'-backup-'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify(copy,null,2),'application/json')}
function restore(){var input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=function(){var file=input.files&&input.files[0];if(!file)return;var r=new FileReader();r.onload=function(){try{var d=JSON.parse(r.result);if(!d||typeof d!=='object'||!d.sessions)throw new Error('Formato inválido');if(!confirm('Restaurar este backup? Os dados atuais deste aparelho serão substituídos.'))return;delete d._backup;d.measurements=d.measurements||[];write(d);alert('Backup restaurado com sucesso.');location.reload()}catch(e){alert('Não foi possível restaurar o backup: '+e.message)}};r.readAsText(file)};input.click()}
function historyHtml(ms){if(!ms.length)return '<div class="muted" style="margin-top:8px">Nenhuma avaliação registrada.</div>';return ms.slice().sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))}).map(function(m){return '<div class="profile-measure"><div class="row"><b>'+datePt(m.date)+'</b><span class="badge">'+esc(m.weight||'—')+' kg</span></div><div class="muted" style="margin-top:5px">Gordura: '+esc(m.fat||'—')+'%'+(m.note?' • '+esc(m.note):'')+'</div></div>'}).join('')}
function openMeasure(){var old=document.getElementById('profileMeasureModal');if(old)old.remove();var modal=document.createElement('div');modal.id='profileMeasureModal';modal.className='modal show profile-modal';modal.innerHTML='<div class="sheet"><div class="title">📋 Registrar avaliação</div><label>Peso (kg)<input id="profileWeight" type="number" step="0.1" inputmode="decimal" placeholder="Ex.: 66,5"></label><label>Gordura corporal (%)<input id="profileFat" type="number" step="0.1" inputmode="decimal" placeholder="Ex.: 19,5"></label><label>Observação<input id="profileNote" placeholder="Como você está se sentindo?"></label><button class="primary" onclick="window.saveProfileMeasure()">Salvar avaliação</button><button class="btn" style="width:100%;margin-top:8px" onclick="document.getElementById(\'profileMeasureModal\').remove()">Cancelar</button></div>';document.body.appendChild(modal)}
function saveMeasure(){var weight=document.getElementById('profileWeight').value,fat=document.getElementById('profileFat').value,note=document.getElementById('profileNote').value;if(!weight&&!fat&&!note){alert('Preencha pelo menos um campo da avaliação.');return}var d=read();d.measurements.push({date:new Date().toISOString(),weight:weight,fat:fat,note:note});write(d);var modal=document.getElementById('profileMeasureModal');if(modal)modal.remove();alert('Avaliação registrada com sucesso.');progress()}
function progress(){var d=read(),n=Object.values(d.sessions).filter(function(s){return s&&s.finished}).length,ms=d.measurements;document.getElementById('main').innerHTML='<div class="title">Progresso</div><div class="card"><div class="grid2"><div class="stat"><div class="num">'+n+'</div><div class="lbl">TREINOS</div></div><div class="stat"><div class="num">'+ms.length+'</div><div class="lbl">AVALIAÇÕES</div></div></div><button class="primary" style="margin-top:12px" onclick="window.openProfileMeasure()">📋 Registrar avaliação</button></div><div class="card"><div class="title" style="font-size:15px">Histórico de avaliações</div>'+historyHtml(ms)+'</div><div class="card"><b>Regra de progressão</b><div class="muted" style="margin-top:7px">Ao atingir o topo da faixa de repetições em todas as séries com boa técnica, aumente a carga na próxima sessão.</div></div>'}
function config(){var d=read(),ms=d.measurements,last=ms.length?ms.slice().sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))})[0]:null,installed=IS_MALE?VERSION:(localStorage.getItem('ttf_version')||window.INSTALLED_VERSION||'1.01'),available=IS_MALE?VERSION:(window.AVAILABLE_VERSION||VERSION),status=installed===available?'<div class="update-status update-ok">✓ Aplicativo atualizado</div>':'<div class="update-status update-warn">⚠️ Atualização disponível</div>';document.getElementById('main').innerHTML='<div class="title">Configurações</div><div class="card"><b>'+esc(APP)+'</b><div class="muted" style="margin-top:7px">Versão instalada: <b>V'+esc(installed)+'</b></div><div style="margin-top:10px">'+status+'</div></div><div id="configUpdate"></div><div class="card"><b>Metas</b><div class="muted" style="line-height:1.7;margin-top:7px">'+GOALS+'</div></div><div class="card"><div class="title" style="font-size:15px">📋 Avaliação corporal</div><div class="muted" style="margin-top:5px">Registre peso, percentual de gordura e uma observação.</div><button class="primary" style="margin-top:10px" onclick="window.openProfileMeasure()">Registrar avaliação</button>'+(last?'<div class="muted" style="margin-top:8px">Última: '+datePt(last.date)+' • '+esc(last.weight||'—')+' kg • '+esc(last.fat||'—')+'% gordura</div>':'')+'<button class="btn" style="width:100%;margin-top:8px" onclick="window.showProfileProgress()">Ver histórico de avaliações</button></div><div class="card"><div class="title" style="font-size:15px">💾 Dados e backup</div><div class="muted" style="margin-top:5px">Seus registros ficam neste aparelho. Faça um backup antes de trocar de aparelho ou realizar mudanças importantes.</div><button class="btn" style="width:100%;margin-top:10px" onclick="window.backupProfile()">💾 Fazer backup completo</button><button class="btn" style="width:100%;margin-top:8px" onclick="window.restoreProfile()">♻️ Restaurar backup</button><button class="btn" style="width:100%;margin-top:8px" onclick="window.exportProfile()">📤 Exportar dados (CSV)</button></div><div class="card"><b>Armazenamento</b><div class="muted" style="margin-top:7px">Os dados são salvos localmente neste aparelho. Atualizações do aplicativo não apagam seu histórico.</div></div>';if(!IS_MALE&&typeof window.renderUpdate==='function')window.renderUpdate(true)}
var css=document.createElement('style');css.id='profileToolsCss';css.textContent='.profile-measure{padding:11px 0;border-top:1px solid var(--line,#e2e4e8)}.profile-measure:first-of-type{margin-top:8px}.profile-modal .sheet{display:block!important;max-height:90vh!important;overflow:auto!important}.profile-modal label{display:block;font-size:11px;color:var(--muted,#737984);margin-top:12px}.profile-modal input{width:100%;margin-top:5px;padding:11px;border:1px solid var(--line,#ddd);border-radius:10px;font-size:16px}.profile-modal .primary{margin-top:14px}';document.head.appendChild(css);
window.openProfileMeasure=openMeasure;window.saveProfileMeasure=saveMeasure;window.backupProfile=backup;window.restoreProfile=restore;window.exportProfile=csv;window.showProfileProgress=progress;
if(IS_MALE){window.renderProgress=progress;window.renderConfig=config}else{window.progress=progress;window.config=config}
})();